### ISSUE TITLE
Custom Component doesn‘t work after upgrade to HASS 2023.6.

### ISSUE THREAD

**Issue by wunni1** [RonnyWinkler/homeassistant.homey#2]
Hello,

after upgrading HASS to 2023.6 i got the following error:

Component error: homey - Exception importing custom_components.homey

running the latest version 1.0.3 of this custom component

**Comment by dxfoxd** [comment]
Got the same error (Running HA Core-2023.6.1.) 

Here my log information:

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 11:30:00 PM (1 occurrences)
Last logged: 11:30:00 PM

Setup failed for custom integration homey: Unable to import component: Exception importing custom_components.homey
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/homey/__init__.py:37
Integration: homey (documentation, issues)
First occurred: 11:30:00 PM (8 occurrences)
Last logged: 11:53:30 PM

Unexpected exception importing component custom_components.homey
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/homey/__init__.py", line 37, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

```

**Comment by RonnyWinkler** [comment]
Please update the component - via HACS update or copy the .py file manually into your HA component folder.
It's already fixed in the current version.

**Comment by dxfoxd** [comment]
Updated (using HACS now) and error is gone. Will track updates from now on :-)

**Comment by RonnyWinkler** [comment]
Thanks for your feedback.

For information and questions, you can also visit the Homey forum thread.
https://community.homey.app/t/app-pro-home-assistant-community-app/71477
